---
# vagrant_scrapybox.yml
- hosts: all
  user: vagrant
  sudo: True

  tasks:
    - name: install packages necessary for scrapy
      action: apt update_cache=yes pkg={{item}} state=installed
      with_items:
        - python-lxml
        - python-pip
        - python-dev
        - libffi-dev
        - vim
        - openvpn

    - name: Install pip packages
      pip: name={{item}} state=present
      with_items:
        - scrapy

    - copy: src=client.conf dest=/etc/openvpn/client.conf owner=root group=root mode=644 backup=yes
    - copy: src=vyprvpn.pas dest=/etc/openvpn/vyprvpn.pas owner=root group=root mode=644 backup=yes
    
    - name: get vyprvpn certificate
      get_url: url=http://www.giganews.com/vyprvpn/ca.vyprvpn.com.crt dest=/etc/openvpn/ca.vyprvpn.com.crt
    
    - service: name=openvpn state=started
